language: python
python:
  - "3.5"
  - "3.4"
  - "3.3"
  - "2.7"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
# install: "sudo apt-get install"
# command to run tests, e.g. python setup.py test
script: python test.py